package HibernatePojos;
// Generated 02-jul-2018 16:14:09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Instituciones generated by hbm2java
 */
public class Instituciones implements java.io.Serializable {

    private Integer idInstitucion;
    private String nombre;
    private String direccion;
    private String ciudad;
    private String pais;
    private Set<Investigadores> investigadoreses = new HashSet<>(0);

    public Instituciones() {
    }

    public Instituciones(String nombre, String direccion, String ciudad, String pais, Set<Investigadores> investigadoreses) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.pais = pais;
        this.investigadoreses = investigadoreses;
    }

    public Integer getIdInstitucion() {
        return this.idInstitucion;
    }

    public void setIdInstitucion(Integer idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public Set<Investigadores> getInvestigadoreses() {
        return this.investigadoreses;
    }

    public void setInvestigadoreses(Set<Investigadores> investigadoreses) {
        this.investigadoreses = investigadoreses;
    }

}
