package HibernatePojos;
// Generated 02-jul-2018 16:14:09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Investigadores generated by hbm2java
 */
public class Investigadores implements java.io.Serializable {

    private Integer idInvestigador;
    private Instituciones instituciones;
    private Boolean borrado;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String correo;
    private String puesto;
    private String password;
    private Set<Publicaciones> publicacioneses = new HashSet<>(0);
    private Set<Publicaciones> publicacioneses_1 = new HashSet<>(0);

    public Investigadores(Instituciones instituciones, Boolean borrado, String nombre, String apellido1, String apellido2, String correo, String puesto, String password, Set<Publicaciones> publicacioneses, Set<Publicaciones> publicacioneses_1) {
        this.instituciones = instituciones;
        this.borrado = borrado;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.correo = correo;
        this.puesto = puesto;
        this.password = password;
        this.publicacioneses = publicacioneses;
        this.publicacioneses_1 = publicacioneses_1;
    }

    public Investigadores() {

    }

    public Integer getIdInvestigador() {
        return this.idInvestigador;
    }

    public void setIdInvestigador(Integer idInvestigador) {
        this.idInvestigador = idInvestigador;
    }

    public Instituciones getInstituciones() {
        return this.instituciones;
    }

    public void setInstituciones(Instituciones instituciones) {
        this.instituciones = instituciones;
    }

    public Boolean getBorrado() {
        return this.borrado;
    }

    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getPuesto() {
        return this.puesto;
    }

    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Publicaciones> getPublicacioneses() {
        return this.publicacioneses;
    }

    public void setPublicacioneses(Set<Publicaciones> publicacioneses) {
        this.publicacioneses = publicacioneses;
    }

    public Set<Publicaciones> getPublicacioneses_1() {
        return this.publicacioneses_1;
    }

    public void setPublicacioneses_1(Set<Publicaciones> publicacioneses_1) {
        this.publicacioneses_1 = publicacioneses_1;
    }

}
