package HibernatePojos;
// Generated 02-jul-2018 16:14:09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones implements java.io.Serializable {

    private Integer idPublicacion;
    private Investigadores investigadores;
    private String titulo;
    private Integer year;
    private Integer firstPage;
    private Integer lastPage;
    private Set<Investigadores> investigadoreses = new HashSet<>();

    public Publicaciones(Investigadores investigadores, String titulo, Integer year, Integer firstPage, Integer lastPage, Set<Investigadores> investigadoreses) {
        this.investigadores = investigadores;
        this.titulo = titulo;
        this.year = year;
        this.firstPage = firstPage;
        this.lastPage = lastPage;
        this.investigadoreses = investigadoreses;
    }

    public Publicaciones() {

    }

    public Integer getIdPublicacion() {
        return this.idPublicacion;
    }

    public void setIdPublicacion(Integer idPublicacion) {
        this.idPublicacion = idPublicacion;
    }

    public Investigadores getInvestigadores() {
        return this.investigadores;
    }

    public void setInvestigadores(Investigadores investigadores) {
        this.investigadores = investigadores;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getFirstPage() {
        return this.firstPage;
    }

    public void setFirstPage(Integer firstPage) {
        this.firstPage = firstPage;
    }

    public Integer getLastPage() {
        return this.lastPage;
    }

    public void setLastPage(Integer lastPage) {
        this.lastPage = lastPage;
    }

    public Set<Investigadores> getInvestigadoreses() {
        return this.investigadoreses;
    }

    public void setInvestigadoreses(Set<Investigadores> investigadoreses) {
        this.investigadoreses = investigadoreses;
    }

}
